### ISSUE TITLE
Show progress for long-running operations

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-launch#10]
When performing long operations (e.g. initial pull etc.) the operation might take seconds or even minutes. As a user I have no idea if the code is hanging or not, and I'm tempted to press CTRL+C.
Is there a way to show progress? At least for those commands for which docker would, like `pull`?

**Comment by csadorf** [comment]
@giovannipizzi Unfortunately, especially the very long running operations such as pull, do not provide a progress indication. See also this related issue: https://github.com/docker/docker-py/issues/2868

However, I have updated the program to use spinners as progress indicator for all long-running progresses. I believe this is the best that we can do for now, but I am open to suggestions.
