### ISSUE TITLE
Instance slows down after some time on local computer

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-launch#129]

**Comment by csadorf** [comment]
Originally reported by @unkcpz , could you comment on this, please?

**Comment by unkcpz** [comment]
I have no solid clue of how that happened and I didn't even encounter it anymore after I clean my disk space. I now suspect it is not aiidalab slow itself but localhost has running something slow down the docker/container. I'll have my eyes on this and give a more detailed monitor/report once I encounter it again.

**Comment by csadorf** [comment]
In that case, I'll close the issue for now. Please re-open it and provide more information should you encounter the problem again. Thanks!
