### ISSUE TITLE
 Disable spinner in debugging mode

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#146]
Spinner is a bit annoying when debugging is enabled.
```sh
$ aiidalab-launch -vv start
[Verbose logging is enabled. (LEVEL=20)
INFO:aiidalab_launch:Configuration file path: /home/hollas/.config/org.aiidalab.aiidalab_launch/config.toml
INFO:aiidalab_launch:Using profile: test
INFO:aiidalab_launch:Starting container 'aiidalab_test'...
Starting container... |INFO:aiidalab_launch:Started container: aiidalab_test (42e544244d4d254b1db30e6806f2756d2ae3167ca3d74e118a1bc5cb1816726a).
done.
Waiting for AiiDAlab instance to get ready... -INFO:aiidalab_launch:Waiting for services to come up (42e544244d4d254b1db30e6806f2756d2ae3167ca3d74e118a1bc5cb1816726a)..
```

I very briefly looked at the code but it wasn't immediately clear how to disable it.

**Comment by csadorf** [comment]
I like the idea to either disable or replace the spinner in cases where the log-level threshold has been reduced.

Have you looked at the spinner context manage, that is used to display it? https://github.com/aiidalab/aiidalab-launch/blob/d01762338f32ad7dcdd06ad7dd76090321426409/aiidalab_launch/util.py#L38

Maybe we could wrap this function in a separate `progress_indicator()` context manager that only displays the spinner in case that the log-level is higher than `logging.INFO`? The progress indicator would either not display anything or simply print dots (`.`). What do you think of that idea?
