### ISSUE TITLE
Don't fail startup if image cannot be downloaded from Dockerhub

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#153]
I am working with a locally built Docker image and it is a little annoying to have to specify `--no-pull` on each startup. I think it would be a reasonable behaviour to emit a warning when the image cannot be downloaded but continue with the local one (if available).

**Comment by csadorf** [comment]
> I am working with a locally built Docker image and it is a little annoying to have to specify `--no-pull` on each startup. I think it would be a reasonable behaviour to emit a warning when the image cannot be downloaded but continue with the local one (if available).

Agreed, I've ran into this many times as well. I see that you have already assigned it to yourself, but please let me know if you need any assistance.
