### ISSUE TITLE
full-stack: RabbitMQ server sometimes does not start

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#158]
When starting the new aiidalab/full-stack image, sometimes the rabbitmq server does not start, and I need to start it manually in the container after startup. I don't know why and not much is written in the logs, except this:

```
bash: running /usr/local/bin/before-notebook.d/30_start-rabbitmq.sh
chmod: cannot access '/home/jovyan/.erlang.cookie': No such file or directory
erlang cookie not created yet.
```

I believe there was already some attempt to resolve the erlang.cookie problem, perhaps the solution is not complete.

@unkcpz have you experienced this as well?

**Comment by unkcpz** [comment]
No, I didn't see this. Where is your home volume mounted? Is a new docker volume created?

**Comment by danielhollas** [comment]
Hmm, good question, I guess typically new docker volume. Will test...

**Comment by danielhollas** [comment]
Actually, the issue happens even when I restart the container with an already existing volume. 
Perhaps this issue should be transferred to the aiidalab-docker-stack repo, I put it here by accident, I don't think this can be solved in `aiidalab-launch`.

**Comment by danielhollas** [comment]
I determined that the issue only happens in my own custom Docker image. I haven't determined the cause yet, but closing the issue here.
