### ISSUE TITLE
Point user to `aiidalab-launch logs` when `start` fails

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-launch#176]
When you try to start a container and it fails, not a lot of information is passed to the user:

```console
❯ aiidalab-launch start
Downloading latest version of 'ghcr.io/aiidalab/full-stack:pr-372'... done.
Starting container...
Error: Startup failed due to an unexpected error.
```

And there seems to be no `--verbose` option either:

```console
❯ aiidalab-launch start --help
Usage: aiidalab-launch start [OPTIONS]

  Start an AiiDAlab instance on this host.

Options:
  --restart                       Restart the container in case that it is
                                  already running.
  --wait INTEGER                  Time to wait after startup until all
                                  services are up. Set to zero to not wait at
                                  all and immediately return.  [default: 120]
  --pull / --no-pull              Specify whether to pull the configured image
                                  prior to the first start of the container.
                                  [default: pull]
  --no-browser                    Do not open AiiDAlab in the browser after
                                  startup. (This is disabled by default if the
                                  wait time is set to zero.)
  --show-ssh-port-forwarding-help
                                  Show guidance on SSH port forwarding.
  -f, --force                     Ignore any warnings and start anyways.
  -p, --profile TEXT              Select profile to use.
  --help                          Show this message and exit.
```

I'm in favor of short error messages by default, that then point out the `--verbose` option for more information on why a `start` command failed.

EDIT:

As pointed out by @danielhollas, it's better to look into the logs with `aiidalab-launch logs`. So we should give these instructions to the user.

**Comment by danielhollas** [comment]
The verbose option is already there, but you need to put it before the start command. Try running aiidalab-launch --help.

However, when the startup fails, it is usually more informative to look at the container logs via the `aiidalab-launch logs` command.

**Comment by mbercx** [comment]
Thanks @danielhollas! Good to know about these commands. Maybe we should point to these options if the `start` command fails?

**Comment by danielhollas** [comment]
The strange thing is that this should already happen, you can grep for this message in the `__main__.py` file.

My guess is that the startup failed very early in the process. Does the logs command show anything? Try running aiidalab-launch -vvv start.

**Comment by mbercx** [comment]
The logs are here, but that's an unrelated issue:

https://github.com/aiidalab/aiidalab-docker-stack/pull/372#issuecomment-1522950855

**Comment by danielhollas** [comment]
Cool, thanks! Just to make sure, are you running the latest version of `aiidalab-launch`?

**Comment by mbercx** [comment]
Well, I'll be damned, I was not! Thanks for the help @danielhollas, I'll close this one then 👍 

```
Error: The AiiDAlab instance failed to start. You can inspect the container output logs with 'aiidalab-launch logs -p test-pr372' and increase the output verbosity with 'aiidalab-launch -vvv start'.
```
