### ISSUE TITLE
NEVER use lastest tag

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-launch#179]
This is one thing I got from JupyterCon23 from the talk of https://github.com/yuvipanda who is one of core developers for jupyter docker-stack. "Never use latest" is one take-home message.
I can also find some relevant articles about it:
- [What's Wrong With The Docker :latest Tag?](https://vsupalov.com/docker-latest-tag/)
- [DO NOT RUN A CONTAINER WITH THE :LATEST TAG](https://cloudmaniac.net/docker-container-never-use-latest-cicd-pipeline/)
- ...

We actually encounter the issue when using it as the default image in `aiidalab-launch`, when there is a new release of aiida-core, it uses the new image automatically. This brings the issue that in @superstar54's live demo, not only when starting the container takes time to pull the new image, but also a critical bug happened.

I propose to use latest aiida-core version tag as the default tag of aiidalab-launch profile. 
@yakutovicha @superstar54 @danielhollas comments?

**Comment by danielhollas** [comment]
I don't find the two linked articles that convincing in our use case, since we build and push images on the CI, and the `latest` tag therefore essentially means "the latest official version". 

> This brings the issue that in @superstar54's live demo, not only when starting the container takes time to pull the new image, but also a critical bug happened.

Could you please describe exactly what happened? What was the bug? To me, this is more of an issue that we need to test more the official released versions (and perhaps release them less often).

> I propose to use latest aiida-core version tag as the default tag of aiidalab-launch profile.

I am not sure I understand your proposal here. The `latest` tag is equivalent to the latest `aiida-core` tag. They only start to differ when we bump the aiida-core version. What `aiida-core` version would you propose to be the default? And how often should the default be updated?

What would make more sense to me is to use the postgres version tag as the default, since supposedly, since updating PSQL is something that the user would typically want to avoid.

What I think is the bigger underlying issue is that in `aiidalab-docker-stack` the images are based on the latest jupyter-stack image, that is updated very often and often breaks us in unexpected ways (see many recent PRs where we needed to pin versions of various jupyter packages). Specifically, we're tracking Python3.9 tag, which is still updated regularly by the jupyter team. It would be more sane for us to track a tag that is not actively updated (e.g. some older Python version), and only update it e.g. once per six months or something. WDYT?

**Comment by danielhollas** [comment]
> What I think is the bigger underlying issue is that in aiidalab-docker-stack the images are based on the latest jupyter-stack image, that is updated very often and often breaks us in unexpected ways (see many recent PRs where we needed to pin versions of various jupyter packages). Specifically, we're tracking Python3.9 tag, which is still updated regularly by the jupyter team. It would be more sane for us to track a tag that is not actively updated (e.g. some older Python version), and only update it e.g. once per six months or something. WDYT?

Hmm, looks like the above is not quite true, the last release of `jupyter/minimal-notebook:python-3.19` was 7 months ago.
So I am not sure where for example issue from https://github.com/aiidalab/aiidalab-home/issues/149 came from.

**Comment by unkcpz** [comment]
>  > This brings the issue that in @superstar54's live demo, not only when starting the container takes time to pull the new image, but also a critical bug happened.
>
> Could you please describe exactly what happened? What was the bug? To me, this is more of an issue that we need to test more the official released versions (and perhaps release them less often).

I was wrong about this, I thought `aiida-2.3.0` is already released and `full-stack:latest` uses `aiida-core==2.3.0`. The issue I mentioned is after the container stopped it cannot start because the `verdi daemon stop` will throw the exception, as also reported by Carlo in the arm64 test and discussed in https://github.com/aiidalab/aiidalab-docker-stack/issues/379. 
@superstar54 show me the aiida-core version inside the container was 2.3.0 so it was the same issue but aiida-core is update not because of using a new docker stack but must be somewhere else. @superstar54 do you remember if you reinstall your customized QEapp or re-installed the AWB before you saw the issue? 

But I still think using `latest` tag is not encouraged, it is true the `aiida-2.2.2` is equal to `latest` but afterall the `latest` is less static than using aiida tag.

**Comment by unkcpz** [comment]
> So I am not sure where for example issue from https://github.com/aiidalab/aiidalab-home/issues/149 came from.

It does not come from the docker stack image but installing `aiidalab-home` will install the new `widgetsnbextension` (as the dependency of `ipywidget`). So we pinned the version inside `aiidalab-home`

**Comment by superstar54** [comment]
I got the error (`Critical: The daemon could not be reached, ...`) when I restart my computer.

**Comment by unkcpz** [comment]
Thanks @superstar54. Yes, that is exactly the issue as reported https://github.com/aiidalab/aiidalab-docker-stack/issues/379. Do you know why you have `aiida-core==2.3.0` rather than `v2.2.2` which is provided by the container? You installed it explicitly or it is updated by other packages (for example if you pin `aiida-quantumespresso==4.3.0` it pines aiida-core to `v2.3.0`).

**Comment by danielhollas** [comment]
> I got the error (Critical: The daemon could not be reached, ...) when I restart my computer.

How exactly did you get this error? (i.e. which commands exactly and where do you see the error?) Daemon cannot be reached is a very general error, it could have been something else.

> I used a customized image, which uses FROM aiidalab/full-stack:aiida-2.2.2

In that case I really don't understand how you could get to aiida-core 2.3.0. We don't have anything imo that would require this version, so unless you went to great lengths to reinstall it, I am puzzled as you could get it to you image.

**Comment by unkcpz** [comment]
> Aiida-core cannot be updated, it is pinned in the image. 

Not fully true, I just check the constrain set in docker stack and it is pinned to a range https://github.com/aiidalab/aiidalab-docker-stack/blob/5a1de2efdf86aab6ab2153eebf9cc728f31d9e68/stack/base/requirements.txt#L1

As for the version constrain set in `aiidalab` by "core-packages", first of all, it will check only through app manager. Meanwhile, there is still way to override the these core-packages by not pinning the `aiida-core` but having dependencies to install the incompatible version of `aiida-core`, I guess in @superstar54's case, he install QeApp or aiida-quantumespresso==4.3.0 (either through `pip` or `aiidalab insntall` or app manager) and it will then override the `aiida-core` version to `2.3.0`.

I don't know the better solution for it, the dilemma happened to this case is app and package break the container which we didn't consider. Maybe we need to pinning aiida-core version in https://github.com/aiidalab/aiidalab-docker-stack/blob/5a1de2efdf86aab6ab2153eebf9cc728f31d9e68/stack/base/requirements.txt#L1?

**Comment by unkcpz** [comment]
> It is still weird that the version got updated, because qeapp requires aiida-core~=2.2

Nope, `aiidalab-qe==23.10.0a0 -> aiida-quantumespresso==4.3.0 -> aiida-core==2.3.0`. 

> How exactly did you install it? Also, what is the pip version?

I installed it from app store, just tick the include pre-release box.
