### ISSUE TITLE
Support Podman

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#196]
Fedora linux comes with Podman pre-installed, might be nice to support it. AFAIK Podman tries to have compatible API with Docker so hopefully this will not be too much work.

Currently, I am getting this error:

```python
Connecting to docker host... 
Unable to communicate with docker on this host. This error usually
indicates that Docker is either not installed on this system, that the
docker service is not started, or that the installation is ill-
configured.  Please follow the instructions at
https://docs.docker.com/get-docker/ to install and start docker.
```

Podman has its own Python API, `podman-py`, but according to [this issue](https://github.com/containers/podman-py/issues/336), `docker-py` that we use here should work as well. I'll take a closer look.

@unkcpz in case you have any experience with Podman, I'd appreciate your thoughts.

**Comment by unkcpz** [comment]
In the issue you linked it says "if can just use docker-py and point it to the podman system service (socket)." 

I guess you need run something as `export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock` to point docker python API to find podman socket to interact.

I don't have experience with podman, but I agree it should be straightforward to support.

**Comment by danielhollas** [comment]
> I guess you need run something as export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock to point docker python API to find podman socket to interact.

Oh, that is very good to know, thanks! Now I am getting permission error, but that should be resolvable without changes to `aiidalab-launch`. I will report back once I get it working and we can extend documentation.

```
Error: Failed to communicate with Docker client: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```
