### ISSUE TITLE
Mapping a specific port

### ISSUE THREAD

**Issue by obgeneralao** [aiidalab/aiidalab-launch#42]
Hi,

Is it possible to map a particular port (i.e. port 5432) so that I can access it outside of the container?

Thanks a lot

**Comment by csadorf** [comment]
@obgeneralao Starting AiiDAlab with the tool will map port 8888 to whatever port is specified in the profile. You can view the profile with: ```aiidalab-launch profiles view default```.

This is what that looks like for me:

```console
$ aiidalab-launch profiles show default
port = 8888
default_apps = [ "aiidalab-widgets-base",]
system_user = "aiida"
image = "aiidalab/aiidalab-docker-stack:latest"
home_mount = "/home/sadorf/aiidalab"
```

That means AiiDAlab will be available on port 8888 on the host. If you like to use port 5432, just edit the profile with `aiidalab-launch profiles edit default` and change the value for the port.

I hope that answers your question, if not, please don't hesitate to reach out again. Thanks!

**Comment by csadorf** [comment]
I assume the question was answered. Please feel free to reach out in case it wasn't.
