### ISSUE TITLE
Image name is image ID after launch

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-launch#45]
With version `aiidalab-launch-2022.1007`, the image name by `docker ps` is the image ID by `docker images`. ~~This cause my vscode can not find the correct config file for the container.~~

**Comment by csadorf** [comment]
Unfortunately I don't exactly follow what you mean. Would you mind elaborating on this?

**Comment by unkcpz** [comment]
Ha~ my bad ;p 
Please check the screenshot below, the `IMAGE ID` become the `IMAGE` in `docker ps`.   I don't think this is a server problem or maybe it is set to have the IMAGE ID as the name? For the vscode, it is just hard to find the configuration file since the name is not meaningful but it is truly there. 

![image](https://user-images.githubusercontent.com/8831685/149919315-db221d3b-ccc9-433b-ac36-46e4ac20495e.png)

![image](https://user-images.githubusercontent.com/8831685/149919238-057c8099-5dce-40cb-b469-341c8c109248.png)

**Comment by csadorf** [comment]
I see, that's odd. And I'm wondering whether that is actually an issue with the tool or something else. We'll have to investigate.

**Comment by unkcpz** [comment]
I have another env that runs AiiDAlab Launch v2021.1003, which does not have this issue.

**Comment by csadorf** [comment]
> I have another env that runs AiiDAlab Launch v2021.1003, which does not have this issue.

Ok, that's great information. Thanks!
